#TODO: remove useless fields
test:
  #unet_path: /work/scratch/lanceschi/output/tests/diffusion_pytorch_model.safetensors
  #txt_encoder_path: /work/scratch/lanceschi/output/tests/model.safetensors
  #imgs_folder:  /work/scratch/lanceschi/output/tests/img

output:
  folder_name: ./selora_outputs
  #folder_lora_name: /loras

dataset:
  dataset_path: ./Datasets/BraTS/trainset
  report_name: metadata.csv
  prompts_for_generation: ./Generation Prompts/metadata_generation_brats.csv
  

default_random_seed: 42
batch_size: 8
lr: 1.e-4
epochs: 150
th: 1.0
rank: 8 # Initial rank to depart from 

model:
  model_id: runwayml/stable-diffusion-v1-5
  #unet_modules: to_v # not being used
  #txt_encoder_modules: v_proj # not being used
  #rank: 8 # not being used
  #expandable: False # not being used
